"""create or update jobs table

Revision ID: 2970e344e95b
Revises: 
Create Date: 2026-08-18 11:41:41.485469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2970e344e95b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('pdf_path', sa.String(length=512), nullable=True))
    op.add_column('jobs', sa.Column('result_path', sa.String(length=512), nullable=True))
    op.add_column('jobs', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('tender_id', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'tender_id')
    op.drop_column('jobs', 'retry_count')
    op.drop_column('jobs', 'page_count')
    op.drop_column('jobs', 'result_path')
    op.drop_column('jobs', 'pdf_path')
    op.drop_column('jobs', 'original_filename')
    # ### end Alembic commands ###
